// Permanent-for-the-run passive items picked at level-up. Each has a
// maxLevel; the derived stats they grant are recomputed every level-up
// (see player.js:recomputeStats) rather than incrementally applied, so
// order of acquisition never matters.
//
// `rarity` (common/uncommon/rare/elite) drives draw odds in
// levelup-options.js -- see RARITY_WEIGHT there. It is not a power label by
// itself; it's "how complex/build-defining is this effect", matching how
// Brotato's own item tiers work (a common is one stat, an elite is a whole
// mechanic, usually with a real cost). Commons/uncommons ship in this pass;
// rare/elite cards (burn, thorns, execute, etc.) are a follow-up pass, once
// the new combat mechanics they need exist.

export const PASSIVES = {
  // ---------------- existing core passives (rarity-tagged, unchanged effects) ----------------
  scope: {
    id: "scope",
    name: "Scope",
    icon: "◎",
    color: "#f87171",
    rarity: "uncommon",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 6}% crit chance, +${lvl * 20}% crit damage`,
    grant: (lvl) => ({ critChance: lvl * 0.06, critDamage: lvl * 0.2 }),
  },
  treads: {
    id: "treads",
    name: "Treads",
    icon: "➤",
    color: "#34d399",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 7}% move speed`,
    grant: (lvl) => ({ moveSpeedMult: lvl * 0.07 }),
  },
  magnet: {
    id: "magnet",
    name: "Magnet",
    icon: "⊙",
    color: "#60a5fa",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 18}% pickup radius`,
    grant: (lvl) => ({ pickupRadiusMult: lvl * 0.18 }),
  },
  plating: {
    id: "plating",
    name: "Plating",
    icon: "▣",
    color: "#a3a3a3",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `-${lvl} flat damage taken (min 1)`,
    grant: (lvl) => ({ armorFlat: lvl }),
  },
  vitality: {
    id: "vitality",
    name: "Vitality",
    icon: "♥",
    color: "#fb7185",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 20} max HP, +${(lvl * 0.4).toFixed(1)} HP/s regen`,
    grant: (lvl) => ({ maxHp: lvl * 20, regen: lvl * 0.4 }),
  },
  battery: {
    id: "battery",
    name: "Battery",
    icon: "⚡",
    color: "#fbbf24",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `-${lvl * 6}% weapon cooldowns`,
    grant: (lvl) => ({ cooldownMult: -lvl * 0.06 }),
  },
  core: {
    id: "core",
    name: "Amplifier Core",
    icon: "◈",
    color: "#c084fc",
    rarity: "uncommon",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 8}% area/size of effects`,
    grant: (lvl) => ({ areaMult: lvl * 0.08 }),
  },
  fourleaf: {
    id: "fourleaf",
    name: "Four-Leaf",
    icon: "☘",
    color: "#4ade80",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 10}% luck (better drops, rarer choices)`,
    grant: (lvl) => ({ luck: lvl * 0.1 }),
  },
  dronebay: {
    id: "dronebay",
    name: "Drone Bay",
    icon: "⟁",
    color: "#38bdf8",
    rarity: "uncommon",
    maxLevel: 8,
    desc: (lvl) => `Summons ${Math.min(3, 1 + Math.floor(lvl / 3))} Combat Drone(s) (+${Math.round(lvl * 15)}% drone damage)`,
    grant: (lvl) => ({ droneMax: Math.min(3, 1 + Math.floor(lvl / 3)), droneDmgMult: 1 + lvl * 0.15 }),
  },
  medicbay: {
    id: "medicbay",
    name: "Field Medic",
    icon: "✚",
    color: "#4ade80",
    rarity: "uncommon",
    maxLevel: 8,
    desc: (lvl) => `Summons a Field Medic (heals ${4 + lvl * 2}/pulse, you + other allies)`,
    grant: (lvl) => ({ medicMax: 1, healPower: 4 + lvl * 2 }),
  },
  vanguardbeacon: {
    id: "vanguardbeacon",
    name: "Vanguard Beacon",
    icon: "⛨",
    color: "#fbbf24",
    rarity: "uncommon",
    maxLevel: 8,
    desc: (lvl) => `Summons a Vanguard ally (+${Math.round(lvl * 25)}% ally HP)`,
    grant: (lvl) => ({ vanguardMax: 1, vanguardHpMult: 1 + lvl * 0.25 }),
  },

  // ---------------- new commons (25) -- one stat, small numbers, maxLevel 8 unless noted ----------------
  overclockChip: {
    id: "overclockChip",
    name: "Overclock Chip",
    icon: "▵",
    color: "#f87171",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 4}% damage`,
    grant: (lvl) => ({ damageMult: lvl * 0.04 }),
  },
  ballisticCoil: {
    id: "ballisticCoil",
    name: "Ballistic Coil",
    icon: "◆",
    color: "#7dd3fc",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 6}% damage from Blaster/Missiles/Drone (Ballistic-tagged weapons)`,
    grant: (lvl) => ({ ballisticDmgMult: lvl * 0.06 }),
  },
  fieldResonator: {
    id: "fieldResonator",
    name: "Field Resonator",
    icon: "✦",
    color: "#facc15",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 6}% damage from Orbiter/Nova (Field-tagged weapons)`,
    grant: (lvl) => ({ fieldDmgMult: lvl * 0.06 }),
  },
  arcCapacitor: {
    id: "arcCapacitor",
    name: "Arc Capacitor",
    icon: "⚡",
    color: "#e879f9",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 10}% Chain Lightning damage (Arc-tagged)`,
    grant: (lvl) => ({ arcDmgMult: lvl * 0.1 }),
  },
  nanoweaveVest: {
    id: "nanoweaveVest",
    name: "Nanoweave Vest",
    icon: "▮",
    color: "#fb7185",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 15} max HP`,
    grant: (lvl) => ({ maxHp: lvl * 15 }),
  },
  regenerator: {
    id: "regenerator",
    name: "Regenerator",
    icon: "♥",
    color: "#fb7185",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${(lvl * 0.3).toFixed(1)} HP/s regen`,
    grant: (lvl) => ({ regen: lvl * 0.3 }),
  },
  deflectorPlate: {
    id: "deflectorPlate",
    name: "Deflector Plate",
    icon: "◇",
    color: "#93c5fd",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `-${lvl * 3}% incoming damage`,
    grant: (lvl) => ({ dmgTakenMult: -lvl * 0.03 }),
  },
  phaseSkitter: {
    id: "phaseSkitter",
    name: "Phase Skitter",
    icon: "≈",
    color: "#67e8f9",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 2}% chance to dodge an attack entirely`,
    grant: (lvl) => ({ dodgeChance: lvl * 0.02 }),
  },
  vampiricRounds: {
    id: "vampiricRounds",
    name: "Vampiric Rounds",
    icon: "❦",
    color: "#f43f5e",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `Heal ${lvl * 2}% of damage you personally deal`,
    grant: (lvl) => ({ lifesteal: lvl * 0.02 }),
  },
  microThrusters: {
    id: "microThrusters",
    name: "Micro-Thrusters",
    icon: "»",
    color: "#34d399",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 5}% move speed`,
    grant: (lvl) => ({ moveSpeedMult: lvl * 0.05 }),
  },
  blinkCapacitor: {
    id: "blinkCapacitor",
    name: "Blink Capacitor",
    icon: "↯",
    color: "#818cf8",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `-${lvl * 8}% dash cooldown`,
    grant: (lvl) => ({ dashCooldownMult: -lvl * 0.08 }),
  },
  scrapCollector: {
    id: "scrapCollector",
    name: "Scrap Collector",
    icon: "◈",
    color: "#fbbf24",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 8}% Cores gained`,
    grant: (lvl) => ({ goldGainMult: lvl * 0.08 }),
  },
  dataSiphon: {
    id: "dataSiphon",
    name: "Data Siphon",
    icon: "◌",
    color: "#a78bfa",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 8}% XP gained`,
    grant: (lvl) => ({ xpGainMult: lvl * 0.08 }),
  },
  signalFlare: {
    id: "signalFlare",
    name: "Signal Flare",
    icon: "▲",
    color: "#fb923c",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `Supply caches arrive ${lvl * 4}% sooner`,
    grant: (lvl) => ({ chestLuck: lvl * 0.04 }),
  },
  extendedMag: {
    id: "extendedMag",
    name: "Extended Mag",
    icon: "▭",
    color: "#94a3b8",
    rarity: "common",
    maxLevel: 5,
    desc: (lvl) => `+${lvl} pierce on Blaster/Turret Drone shots`,
    grant: (lvl) => ({ pierceBonus: lvl }),
  },
  wideChoke: {
    id: "wideChoke",
    name: "Wide Choke",
    icon: "◎",
    color: "#c084fc",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 6}% area/size of effects`,
    grant: (lvl) => ({ areaMult: lvl * 0.06 }),
  },
  recoilCompensator: {
    id: "recoilCompensator",
    name: "Recoil Compensator",
    icon: "⇤",
    color: "#fbbf24",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `-${lvl * 4}% weapon cooldowns`,
    grant: (lvl) => ({ cooldownMult: -lvl * 0.04 }),
  },
  impactRounds: {
    id: "impactRounds",
    name: "Impact Rounds",
    icon: "◉",
    color: "#f97316",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 12}% knockback force`,
    grant: (lvl) => ({ knockbackMult: lvl * 0.12 }),
  },
  staticCharge: {
    id: "staticCharge",
    name: "Static Charge",
    icon: "∴",
    color: "#facc15",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 3}% crit chance`,
    grant: (lvl) => ({ critChance: lvl * 0.03 }),
  },
  adrenalGland: {
    id: "adrenalGland",
    name: "Adrenal Gland",
    icon: "!",
    color: "#ef4444",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 8}% crit damage`,
    grant: (lvl) => ({ critDamage: lvl * 0.08 }),
  },
  reinforcedFrame: {
    id: "reinforcedFrame",
    name: "Reinforced Frame",
    icon: "▣",
    color: "#a3a3a3",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `-${lvl} flat damage taken (min 1)`,
    grant: (lvl) => ({ armorFlat: lvl }),
  },
  coolantLoop: {
    id: "coolantLoop",
    name: "Coolant Loop",
    icon: "❄",
    color: "#7dd3fc",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${(lvl * 0.2).toFixed(1)} HP/s regen`,
    grant: (lvl) => ({ regen: lvl * 0.2 }),
  },
  ionTreads: {
    id: "ionTreads",
    name: "Ion Treads",
    icon: "➤",
    color: "#22d3ee",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 4}% move speed`,
    grant: (lvl) => ({ moveSpeedMult: lvl * 0.04 }),
  },
  salvageDrone: {
    id: "salvageDrone",
    name: "Salvage Drone",
    icon: "⊙",
    color: "#38bdf8",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 10}% pickup radius`,
    grant: (lvl) => ({ pickupRadiusMult: lvl * 0.1 }),
  },
  luckyCache: {
    id: "luckyCache",
    name: "Lucky Cache",
    icon: "☘",
    color: "#4ade80",
    rarity: "common",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 5}% luck (better drops, rarer choices)`,
    grant: (lvl) => ({ luck: lvl * 0.05 }),
  },

  // ---------------- new uncommons (10) -- two stats, tradeoffs, or a first trigger, maxLevel 5 ----------------
  overdriveInjector: {
    id: "overdriveInjector",
    name: "Overdrive Injector",
    icon: "⇈",
    color: "#f97316",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `+${lvl * 8}% damage, +${lvl * 5}% move speed`,
    grant: (lvl) => ({ damageMult: lvl * 0.08, moveSpeedMult: lvl * 0.05 }),
  },
  adaptivePlating: {
    id: "adaptivePlating",
    name: "Adaptive Plating",
    icon: "▨",
    color: "#a3a3a3",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `+${lvl * 2} flat armor, -${lvl * 5}% move speed`,
    grant: (lvl) => ({ armorFlat: lvl * 2, moveSpeedMult: -lvl * 0.05 }),
  },
  salvagersInstinct: {
    id: "salvagersInstinct",
    name: "Salvager's Instinct",
    icon: "◈",
    color: "#fbbf24",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `+${lvl * 12}% Cores gained, +${lvl * 12}% luck`,
    grant: (lvl) => ({ goldGainMult: lvl * 0.12, luck: lvl * 0.12 }),
  },
  nanoSurgeon: {
    id: "nanoSurgeon",
    name: "Nano-Surgeon",
    icon: "✚",
    color: "#4ade80",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `+${(lvl * 0.4).toFixed(1)} HP/s regen, heal ${lvl * 3}% of damage you personally deal`,
    grant: (lvl) => ({ regen: lvl * 0.4, lifesteal: lvl * 0.03 }),
  },
  twinBarrel: {
    id: "twinBarrel",
    name: "Twin Barrel",
    icon: "▭",
    color: "#94a3b8",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `+${lvl} pierce on Blaster/Turret Drone shots, +${lvl * 5}% crit chance`,
    grant: (lvl) => ({ pierceBonus: lvl, critChance: lvl * 0.05 }),
  },
  kineticRebound: {
    id: "kineticRebound",
    name: "Kinetic Rebound",
    icon: "◉",
    color: "#f97316",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `+${lvl * 15}% knockback force, +${lvl * 6}% dodge chance`,
    grant: (lvl) => ({ knockbackMult: lvl * 0.15, dodgeChance: lvl * 0.06 }),
  },
  overchargedRounds: {
    id: "overchargedRounds",
    name: "Overcharged Rounds",
    icon: "▵",
    color: "#f87171",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `+${lvl * 8}% damage, -${lvl * 6}% dodge chance`,
    grant: (lvl) => ({ damageMult: lvl * 0.08, dodgeChance: -lvl * 0.06 }),
  },
  bulkLoader: {
    id: "bulkLoader",
    name: "Bulk Loader",
    icon: "◈",
    color: "#c084fc",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `+${lvl * 8}% area/size of effects, -${lvl * 6}% weapon cooldowns`,
    grant: (lvl) => ({ areaMult: lvl * 0.08, cooldownMult: -lvl * 0.06 }),
  },
  combatStims: {
    id: "combatStims",
    name: "Combat Stims",
    icon: "℠",
    color: "#f43f5e",
    rarity: "uncommon",
    maxLevel: 5,
    desc: (lvl) => `Taking damage below 30% HP grants +${lvl * 4}% speed and +${lvl * 3}% damage for 4s`,
    grant: (lvl) => ({ combatStimsSpeedBonus: lvl * 0.04, combatStimsDmgBonus: lvl * 0.03 }),
  },
  scavengerRig: {
    id: "scavengerRig",
    name: "Scavenger Rig",
    icon: "↻",
    color: "#22d3ee",
    rarity: "uncommon",
    maxLevel: 3,
    desc: (lvl) => `+${lvl} reroll(s) per level-up, +${lvl * 5}% luck`,
    grant: (lvl) => ({ extraRerolls: lvl, luck: lvl * 0.05 }),
  },
};

export const PASSIVE_LIST = Object.values(PASSIVES);
