// Permanent-for-the-run passive items picked at level-up. Each has up to
// 5 levels; the derived stats they grant are recomputed every level-up
// (see player.js:recomputeStats) rather than incrementally applied, so
// order of acquisition never matters.

export const PASSIVES = {
  scope: {
    id: "scope",
    name: "Scope",
    icon: "◎",
    color: "#f87171",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 6}% crit chance, +${lvl * 20}% crit damage`,
    grant: (lvl) => ({ critChance: lvl * 0.06, critDamage: lvl * 0.2 }),
  },
  treads: {
    id: "treads",
    name: "Treads",
    icon: "➤",
    color: "#34d399",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 7}% move speed`,
    grant: (lvl) => ({ moveSpeed: lvl * 0.07 }),
  },
  magnet: {
    id: "magnet",
    name: "Magnet",
    icon: "⊙",
    color: "#60a5fa",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 18}% pickup radius`,
    grant: (lvl) => ({ pickupRadius: lvl * 0.18 }),
  },
  plating: {
    id: "plating",
    name: "Plating",
    icon: "▣",
    color: "#a3a3a3",
    maxLevel: 8,
    desc: (lvl) => `-${lvl} flat damage taken (min 1)`,
    grant: (lvl) => ({ armorFlat: lvl }),
  },
  vitality: {
    id: "vitality",
    name: "Vitality",
    icon: "♥",
    color: "#fb7185",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 20} max HP, +${(lvl * 0.4).toFixed(1)} HP/s regen`,
    grant: (lvl) => ({ maxHp: lvl * 20, regen: lvl * 0.4 }),
  },
  battery: {
    id: "battery",
    name: "Battery",
    icon: "⚡",
    color: "#fbbf24",
    maxLevel: 8,
    desc: (lvl) => `-${lvl * 6}% weapon cooldowns`,
    grant: (lvl) => ({ cooldownMult: -lvl * 0.06 }),
  },
  core: {
    id: "core",
    name: "Amplifier Core",
    icon: "◈",
    color: "#c084fc",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 8}% area/size of effects`,
    grant: (lvl) => ({ areaMult: lvl * 0.08 }),
  },
  fourleaf: {
    id: "fourleaf",
    name: "Four-Leaf",
    icon: "☘",
    color: "#4ade80",
    maxLevel: 8,
    desc: (lvl) => `+${lvl * 10}% luck (better drops, rarer choices)`,
    grant: (lvl) => ({ luck: lvl * 0.1 }),
  },
  dronebay: {
    id: "dronebay",
    name: "Drone Bay",
    icon: "⟁",
    color: "#38bdf8",
    maxLevel: 8,
    desc: (lvl) => `Summons ${Math.min(3, 1 + Math.floor(lvl / 3))} Combat Drone(s) (+${Math.round(lvl * 15)}% drone damage)`,
    grant: (lvl) => ({ droneMax: Math.min(3, 1 + Math.floor(lvl / 3)), droneDmgMult: 1 + lvl * 0.15 }),
  },
  medicbay: {
    id: "medicbay",
    name: "Field Medic",
    icon: "✚",
    color: "#4ade80",
    maxLevel: 8,
    desc: (lvl) => `Summons a Field Medic (heals ${4 + lvl * 2}/pulse, you + other allies)`,
    grant: (lvl) => ({ medicMax: 1, healPower: 4 + lvl * 2 }),
  },
  vanguardbeacon: {
    id: "vanguardbeacon",
    name: "Vanguard Beacon",
    icon: "⛨",
    color: "#fbbf24",
    maxLevel: 8,
    desc: (lvl) => `Summons a Vanguard ally (+${Math.round(lvl * 25)}% ally HP)`,
    grant: (lvl) => ({ vanguardMax: 1, vanguardHpMult: 1 + lvl * 0.25 }),
  },
};

export const PASSIVE_LIST = Object.values(PASSIVES);
